# docs: https://towardsdev.com/self-hosted-url-shortening-with-shlink-web-via-docker-ec9b71926be
version: "3.7"
networks:
   main:
       external: true

x-logging:
  &default-logging
  driver: loki
  options:
    mode: non-blocking
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-external-labels: host=corusm.de,stack=shlink

services:
    shlink-api:
      image: shlinkio/shlink:latest
      container_name: shlink-api
      restart: on-failure
      environment:
        - DEFAULT_DOMAIN=s.corusm.de
        - IS_HTTPS_ENABLED=true
        - DB_DRIVER=mysql
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_HOST=shlink_mysql
      links:
        - shlink_mysql
      depends_on:
        - shlink_mysql
      networks:
        - "main"
      labels:
        - com.centurylinklabs.watchtower.enable=true
        - traefik.enable=true
        - traefik.http.routers.s.entrypoints=https
        - traefik.http.routers.s.rule=Host(`s.corusm.de`)
        - traefik.http.routers.s.tls=true
        - traefik.http.routers.s.tls.certresolver=letsencrypt
        - traefik.tcp.services.s.loadbalancer.server.port=8080
        - traefik.docker.network=main
        # gen-api-key: docker exec -it shlink-api shlink api-key:generate
      logging: *default-logging

    shlink-web:
      image: shlinkio/shlink-web-client
      container_name: shlink-web
      restart: on-failure
      networks:
        - "main"
      labels:
        - com.centurylinklabs.watchtower.enable=true
        - traefik.enable=true
        - traefik.http.routers.shlink.entrypoints=https
        - traefik.http.routers.shlink.rule=Host(`shlink.corusm.de`)
        - traefik.http.routers.shlink.tls=true
        - traefik.http.routers.shlink.tls.certresolver=letsencrypt
        - traefik.tcp.services.shlink.loadbalancer.server.port=80
        - traefik.docker.network=main
      logging: *default-logging

    shlink_mysql:
      container_name: shlink_mysql
      image: mysql
      networks:
        - "main"
      # volumes:
      #     - ./data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shlink
      logging: *default-logging