version: '3.7'

networks:
   main:
       external: true

x-logging:
  &default-logging
  driver: loki
  options:
    mode: non-blocking
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-external-labels: host=corusm.de,stack=mlflow-server

services:
  minio:
    image: minio/minio
    container_name: minio-s3
    networks:
      - "main"
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=meinaccesskey
      - MINIO_ROOT_PASSWORD=GANZSICHERERUNDSEHRLANGERKEY
      - MINIO_BROWSER_REDIRECT_URL=https://minio.corusm.de
      - MINIO_SERVER_URL=https://cdn.corusm.de
    command: server /data --console-address ":9001"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.corusm.de`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=letsencrypt
      - traefik.http.routers.minio.service=minioService
      - traefik.http.services.minioService.loadbalancer.server.port=9001
      - traefik.http.services.minioService.loadbalancer.passhostheader=true

      - traefik.http.routers.cdn.rule=Host(`cdn.corusm.de`)
      - traefik.http.routers.cdn.tls=true
      - traefik.http.routers.cdn.tls.certresolver=letsencrypt
      - traefik.http.routers.cdn.service=cdnService
      - traefik.http.services.cdnService.loadbalancer.server.port=9000
      - traefik.http.services.cdnService.loadbalancer.passhostheader=true

      - traefik.docker.network=main
        # echo $(htpasswd -nb username password) | sed -e s/\\$/\\$\\$/g
    logging: *default-logging

  mlflow:
    image: 'corusm/mlflow-server:latest'
    container_name: mlflow_server
    build: .
    depends_on:
      - minio
    networks:
      - "main"
    volumes:
      - "./mlflow:/mlflow"
    environment:
      AWS_ACCESS_KEY_ID: meinaccesskey
      AWS_SECRET_ACCESS_KEY: GANZSICHERERUNDSEHRLANGERKEY
      AWS_DEFAULT_REGION: us-east-1
      BACKEND_URI: sqlite:////mlflow/mlflow.db
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      ARTIFACT_ROOT: s3://mlflow/
      PROM_DIR: /mlflow/prometheus
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.mlflow.entrypoints=https
      - traefik.http.routers.mlflow.rule=Host(`mlflow.corusm.de`)
      - traefik.http.routers.mlflow.tls=true
      - traefik.http.routers.mlflow.tls.certresolver=letsencrypt
      - traefik.tcp.services.mlflow.loadbalancer.server.port=5000
      - traefik.docker.network=main
      - traefik.http.routers.mlflow.middlewares=traefik-auth
      #- traefik.http.routers.mlflow-secured.middlewares=mlflow-auth
      #- traefik.http.middlewares.mlflow-auth.basicauth.usersfile=/etc/traefik/users
      #- traefik.http.middlewares.mlflow-auth.basicauth.users=test:$$apr1$$fsdfsdfdWlXbW.V9edf34eftkgaN0
      # echo $(htpasswd -nb username password) | sed -e s/\\$/\\$\\$/g
      # Password must be added to file insed the traefik container (currently in treafik/users)
    logging: *default-logging