version: '3.7'

x-logging:
  &default-logging
  driver: loki
  options:
    mode: non-blocking
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-external-labels: host=corusm.de,stack=mattermost

networks:
  main:
    external: true

services:
  mattermost-db:
    container_name: postgres_mattermost
    image: postgres:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - main
    logging: *default-logging

  mattermost-app:
    image: mattermost/mattermost-team-edition
    networks:
      - main
    volumes:
      - /etc/localtime:/etc/localtime:ro
    container_name: mattermost-app
    depends_on:
      - mattermost-db
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@mattermost-db:5432/mattermost?sslmode=disable&connect_timeout=10
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.mattermost.entrypoints=https
      - traefik.http.routers.mattermost.rule=Host(`chat.corusm.de`)
      - traefik.http.routers.mattermost.tls=true
      - traefik.http.routers.mattermost.tls.certresolver=letsencrypt
      - traefik.tcp.services.mattermost.loadbalancer.server.port=8065
      - traefik.docker.network=main
    logging: *default-logging