version: '3.7'

x-logging:
  &default-logging
  driver: loki
  options:
    mode: non-blocking
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-external-labels: host=corusm.de,stack=rss

networks:
  main:
    external: true

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - main
    volumes:
      - ./freshrss:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.rss.entrypoints=https
      - traefik.http.routers.rss.rule=Host(`freshrss.corusm.de`)
      - traefik.http.routers.rss.tls=true
      - traefik.http.routers.rss.tls.certresolver=letsencrypt
      - traefik.tcp.services.rss.loadbalancer.server.port=80
      - traefik.docker.network=main

# TODO: Add SQL Container if needed