version: "3"

x-logging:
    &default-logging
    driver: loki
    options:
        mode: non-blocking
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: host=corusm.de,stack=notebook

networks:
   main:
       external: true

services:
   datascience-notebook:
    image: jupyter/datascience-notebook
    volumes: 
      - /home/niklas/docker/jupiter:/home/jovyan/work
    container_name: datascience-notebook-container
    networks:
      - main
    user: root
    environment:
      - JUPYTER_TOKEN=Salkin
      - CHOWN_EXTRA=/home/jovyan/work
      - GRANT_SUDO=yes
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.notebook.entrypoints=https
      - traefik.http.routers.notebook.rule=Host(`notebook.corusm.de`)
      - traefik.http.routers.notebook.tls=true
      - traefik.http.routers.notebook.tls.certresolver=letsencrypt
      - traefik.tcp.services.notebook.loadbalancer.server.port=80
      - traefik.docker.network=main
    logging: *default-logging