version: '3.7' # 2.2
networks:
    main:
       external: true

services:
    nextcloud:
      image: nextcloud
      container_name: nextcloud
      depends_on:
        - db
      networks:
        - "main"
      labels:
        - traefik.enable=true
        - traefik.http.routers.nextcloud.rule=Host(`cloud.corusm.de`)
        - traefik.http.routers.nextcloud.entrypoints=web
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.routers.nextcloud.middlewares=redirect-to-https@docker
        - traefik.http.routers.nextcloud-secured.rule=Host(`cloud.corusm.de`)
        - traefik.http.routers.nextcloud-secured.tls=true
        - traefik.http.routers.nextcloud-secured.tls.certresolver=myhttpchallenge
        - traefik.http.routers.nextcloud-secured.entrypoints=web-secure
      volumes:
        - /home/niklas/docker/nextcloud:/var/www/html
      environment:
        - MYSQL_ROOT_PASSWORD=niklasabc@12
        - MYSQL_PASSWORD=niklasqwerty@32
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_HOST=db

    db:
      image: mariadb
      container_name: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=niklasabc@12
        - MYSQL_PASSWORD=niklasqwerty@32
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
      networks:
        - "main"
      volumes:
        - /home/niklas/docker/mariadb:/var/lib/mysql